networks:
  dev-network:
    driver: bridge

volumes:
  postgres-data:
  backend-data:

services:
  backend:
    # image: ${DOCKER_REGISTRY-}testaspnetapplication
    build:
      context: .
      dockerfile: TestAspNetApplication/Dockerfile
    ports:
     - "31666:31666"
    networks:
     - dev-network
    volumes:
     - backend-data:/app:rw
    depends_on:
     - postgres_db
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
  postgres_db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=zona1992
      - POSTGRES_DB=nicky_db
    ports:
      - "5432:5432"
    networks:
      - dev-network
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
  redis:
    image: redis:latest
    restart: always
    ports:
    - "6379:6379"
    networks:
      - dev-network